server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672  # Web????? ???? 15672???? ????? 5672??? ?????
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/native-file-repo
#        git:
#          uri: https://github.com/dev-gyus/spring-cloud-config.git
#          username: cjsworbehd13@gmail.com
##          password: vmffkdfpal495!

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh